/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEvents {
  action: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string | null;
  membership_id: string | null;
  metadata: Generated<Json>;
  request_id: string | null;
  tenant_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string | null;
  provider: string;
  provider_subject: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface CpAccessConfig {
  account_id: string;
  admin_invitations_allowed: Generated<boolean>;
  admin_mfa_required: Generated<boolean>;
  allowed_domains: Generated<Json>;
  created_at: Generated<Timestamp>;
  login_google_allowed: Generated<boolean>;
  login_microsoft_allowed: Generated<boolean>;
  login_password_allowed: Generated<boolean>;
  member_mfa_required: Generated<boolean>;
  public_signup_allowed: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface CpAccountProvisioning {
  account_id: string;
  created_at: Generated<Timestamp>;
  last_published_status: string;
  published_at: Timestamp;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CpAccounts {
  access_configured: Generated<boolean>;
  account_key: string;
  account_name: string;
  account_settings_configured: Generated<boolean>;
  cp_revision: Generated<number>;
  cp_status: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  integrations_configured: Generated<boolean>;
  module_settings_configured: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface CpAccountSettingsConfig {
  account_id: string;
  branding_font_color_allowed: Generated<boolean>;
  branding_logo_allowed: Generated<boolean>;
  branding_menu_color_allowed: Generated<boolean>;
  branding_welcome_message_allowed: Generated<boolean>;
  company_calendar_allowed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  org_employers_allowed: Generated<boolean>;
  org_locations_allowed: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface CpIntegrationConfig {
  account_id: string;
  created_at: Generated<Timestamp>;
  data_sync_allowed: boolean | null;
  field_mapping_allowed: boolean | null;
  id: Generated<string>;
  import_enabled_allowed: boolean | null;
  import_rules_allowed: boolean | null;
  integration_key: string;
  is_allowed: boolean;
  payments_surface_allowed: boolean | null;
  updated_at: Generated<Timestamp>;
}

export interface CpModuleConfig {
  account_id: string;
  benefits_enabled: Generated<boolean>;
  created_at: Generated<Timestamp>;
  decisions_saved: Generated<boolean>;
  documents_enabled: Generated<boolean>;
  payments_enabled: Generated<boolean>;
  personal_enabled: Generated<boolean>;
  personal_subpage_saved: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface CpPersonalFamilyConfig {
  account_id: string;
  created_at: Generated<Timestamp>;
  family_key: string;
  id: Generated<string>;
  is_allowed: boolean;
  updated_at: Generated<Timestamp>;
}

export interface CpPersonalFieldConfig {
  account_id: string;
  created_at: Generated<Timestamp>;
  default_selected: boolean;
  family_key: string;
  field_key: string;
  id: Generated<string>;
  is_allowed: boolean;
  updated_at: Generated<Timestamp>;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Invites {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  role: string;
  status: string;
  tenant_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface Memberships {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  invited_at: Generated<Timestamp>;
  role: string;
  status: string;
  suspended_at: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MfaRecoveryCodes {
  code_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface MfaSecrets {
  created_at: Generated<Timestamp>;
  encrypted_secret: string;
  id: Generated<string>;
  is_verified: Generated<boolean>;
  issuer: Generated<string>;
  user_id: string;
  verified_at: Timestamp | null;
}

export interface OutboxMessages {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Json;
  status: Generated<string>;
  type: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface TenantAccountSettings {
  branding_applied_cp_revision: Generated<number>;
  branding_font_color: string | null;
  branding_last_saved_at: Timestamp | null;
  branding_last_saved_by_user_id: string | null;
  branding_logo_url: string | null;
  branding_menu_color: string | null;
  branding_status: Generated<string>;
  branding_version: Generated<number>;
  branding_welcome_message: string | null;
  calendar_applied_cp_revision: Generated<number>;
  calendar_last_saved_at: Timestamp | null;
  calendar_last_saved_by_user_id: string | null;
  calendar_observed_dates: Generated<Json>;
  calendar_status: Generated<string>;
  calendar_version: Generated<number>;
  created_at: Generated<Timestamp>;
  org_employers: Generated<Json>;
  org_locations: Generated<Json>;
  org_structure_applied_cp_revision: Generated<number>;
  org_structure_last_saved_at: Timestamp | null;
  org_structure_last_saved_by_user_id: string | null;
  org_structure_status: Generated<string>;
  org_structure_version: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantFieldConfig {
  applied_cp_revision: Generated<number>;
  created_at: Generated<Timestamp>;
  family_key: string;
  field_key: string;
  included: Generated<boolean>;
  last_saved_at: Timestamp | null;
  last_saved_by_user_id: string | null;
  masked: Generated<boolean>;
  required: Generated<boolean>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantPersonalFamilyState {
  applied_cp_revision: Generated<number>;
  created_at: Generated<Timestamp>;
  family_key: string;
  last_saved_at: Timestamp | null;
  last_saved_by_user_id: string | null;
  review_decision: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Tenants {
  admin_invite_required: Generated<boolean>;
  allowed_email_domains: Generated<Json>;
  allowed_sso: Generated<string[]>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  member_mfa_required: Generated<boolean>;
  name: string;
  public_signup_enabled: Generated<boolean>;
  setup_completed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantSectionFields {
  created_at: Generated<Timestamp>;
  field_key: string;
  section_id: string;
  sort_order: Generated<number>;
  tenant_id: string;
}

export interface TenantSections {
  applied_cp_revision: Generated<number>;
  created_at: Generated<Timestamp>;
  last_saved_at: Timestamp | null;
  last_saved_by_user_id: string | null;
  section_id: string;
  section_name: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface TenantSetupSectionState {
  applied_cp_revision: Generated<number>;
  created_at: Generated<Timestamp>;
  last_reviewed_at: Timestamp | null;
  last_reviewed_by_user_id: string | null;
  last_saved_at: Timestamp | null;
  last_saved_by_user_id: string | null;
  last_transition_at: Generated<Timestamp>;
  last_transition_reason_code: string | null;
  section_key: string;
  status: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface TenantSetupState {
  applied_cp_revision: Generated<number>;
  created_at: Generated<Timestamp>;
  last_reviewed_at: Timestamp | null;
  last_reviewed_by_user_id: string | null;
  last_saved_at: Timestamp | null;
  last_saved_by_user_id: string | null;
  last_transition_at: Generated<Timestamp>;
  last_transition_reason_code: string | null;
  overall_status: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_events: AuditEvents;
  auth_identities: AuthIdentities;
  cp_access_config: CpAccessConfig;
  cp_account_provisioning: CpAccountProvisioning;
  cp_account_settings_config: CpAccountSettingsConfig;
  cp_accounts: CpAccounts;
  cp_integration_config: CpIntegrationConfig;
  cp_module_config: CpModuleConfig;
  cp_personal_family_config: CpPersonalFamilyConfig;
  cp_personal_field_config: CpPersonalFieldConfig;
  email_verification_tokens: EmailVerificationTokens;
  invites: Invites;
  memberships: Memberships;
  mfa_recovery_codes: MfaRecoveryCodes;
  mfa_secrets: MfaSecrets;
  outbox_messages: OutboxMessages;
  password_reset_tokens: PasswordResetTokens;
  tenant_account_settings: TenantAccountSettings;
  tenant_field_config: TenantFieldConfig;
  tenant_personal_family_state: TenantPersonalFamilyState;
  tenant_section_fields: TenantSectionFields;
  tenant_sections: TenantSections;
  tenant_setup_section_state: TenantSetupSectionState;
  tenant_setup_state: TenantSetupState;
  tenants: Tenants;
  users: Users;
}
