/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string>;

export interface AuditEvents {
  action: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip: string | null;
  membership_id: string | null;
  metadata: Generated<Json>;
  request_id: string | null;
  tenant_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password_hash: string | null;
  provider: string;
  provider_subject: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface EmailVerificationTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Invites {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  role: string;
  status: string;
  tenant_id: string;
  token_hash: string;
  used_at: Timestamp | null;
}

export interface Memberships {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  invited_at: Generated<Timestamp>;
  role: string;
  status: string;
  suspended_at: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface MfaRecoveryCodes {
  code_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface MfaSecrets {
  created_at: Generated<Timestamp>;
  encrypted_secret: string;
  id: Generated<string>;
  is_verified: Generated<boolean>;
  issuer: Generated<string>;
  user_id: string;
  verified_at: Timestamp | null;
}

export interface OutboxMessages {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Json;
  status: Generated<string>;
  type: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Tenants {
  allowed_email_domains: Generated<Json>;
  allowed_sso: Generated<string[]>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  member_mfa_required: Generated<boolean>;
  name: string;
  public_signup_enabled: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  audit_events: AuditEvents;
  auth_identities: AuthIdentities;
  email_verification_tokens: EmailVerificationTokens;
  invites: Invites;
  memberships: Memberships;
  mfa_recovery_codes: MfaRecoveryCodes;
  mfa_secrets: MfaSecrets;
  outbox_messages: OutboxMessages;
  password_reset_tokens: PasswordResetTokens;
  tenants: Tenants;
  users: Users;
}
